locations/urls.py
from django.urls import path

from . import views

app_name = 'locations'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('<int:location_id>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:location_id>/', views.UpdatePostView.as_view(), name='update'),
    path('delete/<int:location_id>/', views.DeletePostView.as_view(), name='delete'),
    path('<int:location_id>/comment/', views.create_Comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('posts_by_category/<int:pk>', views.CategoryPostView.as_view(), name='posts_by_category'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

trippin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('locations/', include('locations.urls')),
    path('admin/', admin.site.urls),
]

locations/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.URLField(max_length=500, null=True)

    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    name = models.CharField(max_length=200)
    travel_year = models.IntegerField()
    image_url = models.URLField(max_length=500, null=True)
    score = models.CharField(max_length=3)
    touristic_point = models.CharField(max_length=200)
    analysis = models.CharField(max_length=500)
    categories = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    location = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'
    

staticpages/models.py
from django.db import models

# Create your models here.

locations/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'travel_year',
            'image_url',
            'score',
            'touristic_point',
            'analysis',
            'categories'
        ]
        labels = {
            'name': 'Location',
            'travel_year': 'Travel Year',
            'image_url': 'Location Image',
            'score': 'Trippin Score',
            'touristic_point' : 'Highlight',
            'analysis': 'Analysis',
            'categories': 'Categories'
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'User',
            'text': 'Comment',
        }

locations/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView
from django.views.generic.edit import UpdateView, DeleteView

class PostDetailView(DetailView):
    model = Post
    template_name = 'locations/detail.html'
    context_object_name = 'location'
    pk_url_kwarg = 'location_id'

class PostListView(ListView):
    model = Post
    template_name = 'locations/index.html'
    context_object_name = 'location_list'

class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'locations/create.html'
    success_url = reverse_lazy('locations:index') 

class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'locations/update.html'
    pk_url_kwarg = 'location_id'
    context_object_name = 'location'

    def get_success_url(self):
        return reverse_lazy('locations:detail', kwargs={'location_id': self.object.id})

    def get_object(self, queryset=None):
        location_id = self.kwargs.get(self.pk_url_kwarg)
        return get_object_or_404(Post, pk=location_id)


class DeletePostView(DeleteView):
    model = Post
    template_name = 'locations/delete.html'
    context_object_name = 'location'
    success_url = reverse_lazy('locations:index') 

    def get_object(self, queryset=None):
        location_id = self.kwargs.get('location_id')
        return get_object_or_404(Post, pk=location_id)
    
def create_Comment(request, location_id):
    location = get_object_or_404(Post, pk=location_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            location=location)
            comment.save()
            return HttpResponseRedirect(
                reverse_lazy('locations:detail', args=(location_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'location': location}
    return render(request, 'locations/comment.html', context)

class CategoryListView(ListView):
    model = Category
    template_name = 'locations/categories.html'

class CategoryPostView(DetailView):
    model = Category
    template_name = 'locations/posts_by_category.html'

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

locations/templates/locations/categories.html
{% extends 'base.html' %}

{% block title %}
Categories
{% endblock title %}

{% block content %}
<div class="location-pages-title">
    <h2>All Categories</h2>
</div>

<section>
    {% for category in category_list %}
    <article class="category-page">
        <a href="{% url 'locations:posts_by_category' category.id %}">
            <section class="category-section">
                <img src="{{ category.image }}" class="category-image" alt="{{category.name}} Category Image">
                <div class="category-content">
                    <h3>{{category.name}}</h3>
                    <p>{{category.description}}</p>
                </div>
            </section>
        </a>
        {% endfor %}

</section>

{% endblock content %}

locations/templates/locations/comment.html
{% extends 'base.html' %}

{% block content %}
<section class="add-comment-section">
    <h2>Comment the trip to {{ location.name }}</h2>

    <form action="{% url 'locations:comment' location.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="comment-button">Comment</button>
    </form>
</section>
<p><a href="{% url 'locations:detail' location.id %}" class="create-button">
        << Travel Page</a>
</p>
{% endblock content %}

locations/templates/locations/create.html
{% extends 'base.html' %} {% block content %}
<form method="POST" action="{% url 'locations:create' %}" class="creation-form">
    <h2>Add New Trip</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="create-button">Create</button>
</form>

{% endblock content %}

locations/templates/locations/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'locations:delete' location.id %}" method="post">
    {% csrf_token %}
    <section id="delete-section">
        <h2>
            Are you sure that you want to delete the trip to "{{ location.name }}"?
        </h2>
        <section class="delete-image"></section>
        <button type="submit" class="create-button">Delete</button>
    </section>
</form>
{% endblock content %}

locations/templates/locations/detail.html
{% extends 'base.html' %} {% block title %} {{ location.name }} {% endblock title %}
<main>

    {% block content %}
    <div class="location-pages-title">
        <h2>Detailing the trip to {{ location.name }} ({{ location.travel_year }})</h2>
    </div>

    <section class="dados-de-viagem">
        <img src="{{ location.image_url }}" alt="Imagem da viagem para {{ location.name}}" />
        <ul>
            <li>Where: {{ location.name }}</li>
            <li>When: {{ location.travel_year }}</li>
            <li>Trippin Score: {{ location.score }}/5</li>
            <li>Highlight: {{ location.touristic_point }}</li>
            <li class="location-analysis">Description: {{ location.analysis }}</li>
            <li id="edit-button"><a href="{% url 'locations:update' location.id %}">Edit</a></li>
            <li id="delete-button"><a href="{% url 'locations:delete' location.id %}">Delete</a></li>
        </ul>
    </section>
    <section class='comment-section'>
        <h3>Categories</h3>
        {% if location.categories.all %}
        {% for category in location.categories.all%}
        <div class="category-div">
            <a href="{% url 'locations:posts_by_category' category.id %}">
                <p class="category-displayed">{{ category.name}}</p>
            </a>
            {% endfor%}
            {%endif%}
        </div>
        </div>
        <h3>Comments</h3>
        <ul>
            {% if location.comment_set.all %}
            {% for comment in location.comment_set.all %}
            <figure class="comment-space">
                <figcaption>In {{ comment.date }} User {{ comment.author }} said:</figcaption>
                <blockquote>
                    "{{ comment.text }}"
                </blockquote>
            </figure>
            {% endfor %}
            {% else %}
            <p>There's no comments for this travel yet</p>
            {% endif %}
        </ul>
        <a href="{% url 'locations:comment' location.pk %}"><button class="comment-button">Comment</button></a>
    </section>

    {% endblock content %}
</main>

locations/templates/locations/index.html
{% extends 'base.html' %} {% block content %}
<div class="location-pages-title">
    <h2>All Locations</h2>
</div>
{% if location_list %}
<section class="lista-de-cards">
    {% for location in location_list %}
    <article class="card">
        <a href="{% url 'locations:detail' location.id %}"><img src="{{ location.image_url }}"
                alt="Location image {{ location.name }}" /></a>
        <p>{{ location.name }} ({{ location.travel_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Locations not found.</p>
{% endif %}
<a href="{% url 'locations:create' %}">
    <p class="create-button">Add Location</p>
</a>
{% endblock content %}

locations/templates/locations/posts_by_category.html
{% extends 'base.html' %} {% block content %}
<div class="location-pages-title">
    <h2>Locations in {{ category.name }}</h2>
</div>
{% if category.post_set.all %}
<section class="lista-de-cards">
    {% for locations in category.post_set.all %}
    <article class="card">
        <a href="{% url 'locations:detail' locations.id %}"><img src="{{ locations.image_url }}"
                alt="locations image {{ locations.name }}" /></a>
        <p>{{ locations.name }} ({{ locations.travel_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Locations not found.</p>
{% endif %} {% endblock content %}

locations/templates/locations/update.html
{% extends 'base.html' %} {% block content %}
<form method="POST" action="{% url 'locations:update' location.id%}" class="creation-form">
    <h2>Edit Trip</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="create-button">Update</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <header>
        <div class="logo"><a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a></div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'locations:index' %}">Locations</a></li>
                <li><a href="{% url 'locations:categories' %}">Categories</a></li>
                <li><a href="#">About Us</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <p>&copy; 2023 Felipe Férrer. All rights reserved.</p>
    </footer>

</body>

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}
{% block title %}
Página Inicial
{% endblock title %}
{% block content %}
<section class="main-section">
    <div class="overlay">
        <h1>Explore the World with Trippin</h1>
        <p class="slogan">Feel the Trip</p>
    </div>
    {% endblock content %}